"""Init V2

Revision ID: f10a0e613d4f
Revises: 
Create Date: 2026-06-28 00:26:19.958607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10a0e613d4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=255), nullable=True),
    sa.Column('crime_type', sa.String(length=255), nullable=True),
    sa.Column('crime_taxonomy_code', sa.String(length=100), nullable=True),
    sa.Column('crime_description', sa.Text(), nullable=True),
    sa.Column('defendant_age', sa.Integer(), nullable=True),
    sa.Column('defendant_prior_record', sa.Boolean(), nullable=True),
    sa.Column('defendant_ses', sa.String(length=100), nullable=True),
    sa.Column('defendant_mental_health', sa.Text(), nullable=True),
    sa.Column('defendant_cooperation', sa.Boolean(), nullable=True),
    sa.Column('victim_type', sa.String(length=100), nullable=True),
    sa.Column('harm_severity', sa.Text(), nullable=True),
    sa.Column('actual_sentence_type', sa.String(length=100), nullable=True),
    sa.Column('actual_sentence_duration_months', sa.Float(), nullable=True),
    sa.Column('actual_sentence_detail', sa.Text(), nullable=True),
    sa.Column('case_context', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('confidence_breakdown', sa.JSON(), nullable=True),
    sa.Column('layer1_result', sa.JSON(), nullable=True),
    sa.Column('layer2_result', sa.JSON(), nullable=True),
    sa.Column('layer3_result', sa.JSON(), nullable=True),
    sa.Column('layer4_result', sa.JSON(), nullable=True),
    sa.Column('layer5_result', sa.JSON(), nullable=True),
    sa.Column('layer6_result', sa.JSON(), nullable=True),
    sa.Column('verdict_classification', sa.String(length=50), nullable=True),
    sa.Column('recommended_range_min_months', sa.Float(), nullable=True),
    sa.Column('recommended_range_max_months', sa.Float(), nullable=True),
    sa.Column('full_reasoning_chain', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('layer_challenged', sa.Integer(), nullable=True),
    sa.Column('challenge_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('layer', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('access_date', sa.DateTime(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citations')
    op.drop_table('challenges')
    op.drop_table('analyses')
    op.drop_table('cases')
    # ### end Alembic commands ###
